// Sova Unified Directory Data
// Last Updated: 2025-12-12
// Version 4.0 - Plain English descriptions verified against sources

const directoryData = [
  // ============================================================
  // SOVA
  // ============================================================
  { name: "Sova", description: "Free tool that asks you questions to figure out what's wrong with your business — no consultant needed.", url: "https://getsova.com.au", state: "National", category: "Tool", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },

  // ============================================================
  // GOVERNMENT GRANTS - Federal (Funding)
  // ============================================================
  { name: "Industry Growth Program", description: "Government matches what you spend on building your product (you put in $1, they put in $1). Two steps: free advice first, then the money. Must fit national priorities like manufacturing or renewables.", url: "https://business.gov.au/grants-and-programs/industry-growth-program", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "$50K - $5M (matched)" },
  { name: "Business Research and Innovation Initiative (BRII)", description: "Government posts specific problems they want solved. If your solution is chosen, they pay you to build it. You keep the ownership of what you create.", url: "https://business.gov.au/grants-and-programs/business-research-and-innovation-initiative", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Challenge-based rounds", funding: "$100K - $1M" },
  { name: "Entrepreneur's Programme", description: "Government pays up to half the cost of getting your product to market. Must have under $20M revenue. Free money — no repayment, no ownership given up.", url: "https://business.gov.au/grants-and-programs", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $1M" },
  { name: "Export Market Development Grant (EMDG)", description: "Get money back for costs trying to sell overseas — trade shows, marketing, travel. Claim after you've spent the money.", url: "https://www.austrade.gov.au/australian/export/export-grants", state: "National", category: "Grant", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $770K total" },
  { name: "R&D Tax Incentive", description: "Get up to 43.5% of your research costs back as a tax refund. If you're building something new and experimenting, you probably qualify. Claim with your annual tax return.", url: "https://business.gov.au/grants-and-programs/research-and-development-tax-incentive", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Claim annually", funding: "Up to 43.5% of R&D costs back" },
  { name: "CSIRO Kick-Start Program", description: "Work with Australia's top scientists to solve a technical problem. You put in up to $50K, they match it and give you access to their labs. For science-based startups.", url: "https://www.csiro.au/en/work-with-us/funding-programs", state: "National", category: "Grant", need: "Funding", stages: ["Validation"], identity: [], industry: ["DeepTech"], timeline: "Apply anytime", funding: "Up to $50K (matched)" },
  { name: "Boosting Female Founders", description: "DISCONTINUED as of May 2024. No new rounds planned. Was grants for women-founded businesses.", url: "https://business.gov.au/grants-and-programs/boosting-female-founders-initiative", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Program closed", funding: "N/A" },

  // ============================================================
  // GOVERNMENT GRANTS - State (Funding)
  // ============================================================
  { name: "NSW MVP Ventures Program", description: "NSW Government money to build your first working product. For very early startups who need cash to build and test.", url: "https://www.investment.nsw.gov.au/mvp", state: "NSW", category: "Grant", need: "Funding", stages: ["Validation"], identity: [], industry: [], timeline: "Check website", funding: "$25K - $200K" },
  { name: "LaunchVic Startup Grants", description: "Victoria's startup agency with various grants throughout the year. Some small, some large. Check their website for what's open now.", url: "https://launchvic.org", state: "VIC", category: "Grant", need: "Funding", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Various programs", funding: "$10K - $500K" },
  { name: "Advance Queensland - Ignite Ideas Fund", description: "Queensland money for startups ready to sell and grow. You've built something — now you need help scaling it.", url: "https://advance.qld.gov.au", state: "QLD", category: "Grant", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Check for rounds", funding: "$50K - $500K" },
  { name: "SA Seed-Start Program", description: "South Australia matches what you put in. For SA-based tech startups only.", url: "https://www.innovationandskills.sa.gov.au", state: "SA", category: "Grant", need: "Funding", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "Opens March 2026", funding: "Up to $100K (matched)" },
  { name: "New Industries and Innovation Fund", description: "WA Government fund for businesses diversifying beyond mining. Various streams available.", url: "https://www.wa.gov.au/organisation/department-of-jobs-tourism-science-and-innovation", state: "WA", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Ongoing", funding: "Varies" },
  { name: "Innovation Booster Grant", description: "Quick WA grant for small businesses. 75% paid upfront so you're not out of pocket.", url: "https://www.wa.gov.au/organisation/department-of-energy-and-economic-diversification/new-industries-and-innovation-fund-innovation-booster-grant", state: "WA", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $40K" },
  { name: "Tasmania Business Growth Programs", description: "Various small grants for Tasmanian businesses. Good starting point for local founders.", url: "https://www.business.tas.gov.au", state: "TAS", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Ongoing", funding: "Varies" },
  { name: "ACT Priority Investment Program", description: "Canberra funding for businesses in the innovation precinct.", url: "https://www.act.gov.au/business", state: "ACT", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Ongoing", funding: "Varies" },
  { name: "NT Business Innovation Support", description: "Northern Territory grants for innovative businesses. Less competitive than southern states.", url: "https://business.nt.gov.au", state: "NT", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Ongoing", funding: "Varies" },
  { name: "Business Innovation Program NT", description: "NT Government grants plus a business advisor. Helps with product development and finding markets.", url: "https://business.nt.gov.au/grants-and-funding", state: "NT", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $30K" },

  // ============================================================
  // WOMEN FOUNDER FUNDING
  // ============================================================
  { name: "Alice Anderson Fund", description: "Investment fund only for women founders in Victoria. They give you money in exchange for part-ownership of your company.", url: "https://launchvic.org/alice-anderson-fund", state: "VIC", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Apply anytime", funding: "$50K - $500K" },
  { name: "Queensland Female Founders Fund", description: "If you're a woman founder in QLD with an investor ready, the government adds $1 for every $3 your investor puts in.", url: "https://advance.qld.gov.au", state: "QLD", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Check for rounds", funding: "$50K - $200K" },
  { name: "Fearless Innovator Grant", description: "SA grants for women entrepreneurs. Two streams: Scale-Up (bigger) and Accelerate (earlier stage).", url: "https://www.innovationandskills.sa.gov.au", state: "SA", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Opens May 2026", funding: "$20K - $60K" },
  { name: "Coralus (formerly SheEO)", description: "Women funding women. Apply for a 0% interest loan funded by a community of women supporters. Very founder-friendly — no ownership given up.", url: "https://coralus.world", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Apply anytime", funding: "$50K - $100K loan (0% interest)" },
  { name: "Scale Investors", description: "Group of wealthy individuals who only invest in women-founded companies. You get money but give up part-ownership.", url: "https://www.scaleinvestors.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Apply anytime", funding: "$50K - $500K" },
  { name: "Westpac Businesses of Tomorrow", description: "$50K cash plus mentoring. No repayment, no ownership given up. Has a stream for women founders.", url: "https://www.westpac.com.au/business-banking/business-of-tomorrow", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "2026 dates TBA", funding: "$50K + mentoring" },
  { name: "Westpac UNSW 10x Accelerator Scholarships", description: "$20K scholarships for women and non-binary founders joining UNSW's accelerator. Covers living costs while you focus on your startup.", url: "https://www.westpac.com.au/help/community/female-founders", state: "NSW", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: ["Women"], industry: [], timeline: "2026 dates TBA", funding: "$20K scholarship" },
  { name: "Heads Over Heels", description: "Network of senior women executives who open doors for women founders. Not funding — access to powerful people.", url: "https://www.headsoverheels.org.au", state: "National", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: ["Women"], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Rare Birds", description: "Community for women entrepreneurs. Events, mentoring, and leadership programs.", url: "https://rarebirds.co", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "-", funding: "-", cost: "From $99/year" },

  // ============================================================
  // CROWDFUNDING PLATFORMS (Funding)
  // ============================================================
  { name: "Birchal", description: "Raise money from everyday people. Hundreds of small investors buy shares in your company instead of one big investor. Great for consumer brands where customers want to be part of the journey.", url: "https://www.birchal.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "$50K - $5M", cost: "6-8% of what you raise" },
  { name: "OnMarket", description: "Similar to Birchal — regular people invest by buying shares. Second largest platform in Australia.", url: "https://www.onmarket.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "$50K - $5M", cost: "Success fee applies" },
  { name: "VentureCrowd", description: "Crowdfunding for larger investors (typically wealthy individuals). Fewer backers but bigger cheques.", url: "https://www.venturecrowd.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "$100K - $5M" },
  { name: "Pozible", description: "People pledge money for your product when it's ready — not shares. Great for testing if people actually want what you're building before you build it.", url: "https://www.pozible.com", state: "National", category: "Investor", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Apply anytime", funding: "$1K - $500K", cost: "5% of what you raise" },
  { name: "Kickstarter", description: "World's most famous crowdfunding. People pre-order your product before you make it. Best for physical products and creative projects with global appeal.", url: "https://www.kickstarter.com", state: "National", category: "Investor", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Apply anytime", funding: "$1K - $1M+", cost: "5% of what you raise" },
  { name: "Indiegogo", description: "Like Kickstarter but more flexible — you can keep the money even if you don't hit your target.", url: "https://www.indiegogo.com", state: "National", category: "Investor", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Apply anytime", funding: "$1K - $1M+", cost: "5% of what you raise" },

  // ============================================================
  // VENTURE CAPITAL - Major Funds (Funding)
  // ============================================================
  { name: "Blackbird Ventures", description: "Australia's biggest and most famous VC. They invest other people's money in startups in exchange for ownership. Early backers of Canva. Very hard to get — they see thousands and pick a few.", url: "https://blackbird.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "$500K - $50M+" },
  { name: "Airtree Ventures", description: "Top Australian VC. Backed Linktree. They share free resources for founders on their website. Very selective.", url: "https://airtree.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "$1M - $20M+" },
  { name: "Square Peg Capital", description: "Major VC that also invests in Israel and SE Asia. Backed Canva and Airwallex. Looking for startups that could be huge globally.", url: "https://squarepegcap.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "$1M - $50M+" },
  { name: "Main Sequence Ventures", description: "Backed by CSIRO (Australia's science agency). For 'deep tech' — startups based on serious science like AI, space, climate, healthcare.", url: "https://mseq.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["DeepTech", "CleanTech", "HealthTech", "AgTech"], timeline: "Always open", funding: "$500K - $20M+" },
  { name: "Skip Capital", description: "Run by Atlassian co-founder Scott Farquhar. Invests in transformative tech companies across stages.", url: "https://www.skipcapital.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Varies" },
  { name: "Grok Ventures", description: "Mike Cannon-Brookes' (Atlassian) personal fund. Strong focus on climate and clean tech.", url: "https://www.grokventures.com", state: "National", category: "Investor", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: ["CleanTech", "DeepTech"], timeline: "Always open", funding: "Varies" },
  { name: "Carthona Capital", description: "VC backing early-stage founders building category-defining companies. Less famous than Blackbird but solid reputation.", url: "https://www.carthona.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Varies" },
  { name: "Folklore Ventures", description: "Early-stage Australian and NZ startups. Software and marketplaces. Smaller fund so more accessible.", url: "https://www.folklorevc.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Varies" },
  { name: "Rampersand", description: "Specialises in B2B software — meaning you sell to businesses, not consumers.", url: "https://rampersand.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Varies" },
  { name: "Right Click Capital", description: "Invests very early — even just an idea and small team. More accessible than larger VCs.", url: "https://rightclickcapital.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Varies" },
  { name: "Artesian", description: "Multiple funds covering different stages. Also does impact investing (companies solving social/environmental problems).", url: "https://artesianinvest.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Always open", funding: "Varies" },

  // ============================================================
  // VENTURE CAPITAL - Specialist Funds (Funding)
  // ============================================================
  { name: "EVP (Equity Venture Partners)", description: "Only invests in B2B SaaS — software businesses pay for monthly (like Slack or Xero).", url: "https://evp.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "$500K - $5M" },
  { name: "AfterWork Ventures", description: "Experienced startup people who invest together in early Australian startups. Operators, not just investors — more approachable.", url: "https://afterwork.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: [], timeline: "Always open", funding: "Varies" },
  { name: "Tidal Ventures", description: "Australian startups with potential to grow globally, especially into the US.", url: "https://tidal.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: [], timeline: "Always open", funding: "Varies" },
  { name: "Flying Fox Ventures", description: "Early-stage investor. Software, health, and climate. Smaller fund so more accessible.", url: "https://flyingfox.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: ["Tech", "HealthTech", "CleanTech"], timeline: "Always open", funding: "Varies" },
  { name: "Transition Level Investments", description: "Steve Baxter (Shark Tank Australia). Invests his own money and brings hands-on experience.", url: "https://transitionlevel.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Always open", funding: "Varies" },
  { name: "Giant Leap", description: "Impact investor — only backs companies creating positive social or environmental change.", url: "https://giantleap.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["CleanTech"], timeline: "Always open", funding: "Varies" },
  { name: "Tenacious Ventures", description: "Australia's specialist for AgTech and food tech. They understand farming and food.", url: "https://www.tenacious.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["AgTech"], timeline: "Always open", funding: "Varies" },
  { name: "Taronga Ventures", description: "PropTech specialist — startups changing how we buy, sell, build, or manage property.", url: "https://www.tarongaventures.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["PropTech"], timeline: "Always open", funding: "Varies" },
  { name: "Our Innovation Fund", description: "Backs 'for-purpose' businesses — companies solving social or environmental problems, not just making money.", url: "https://ourinnovationfund.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["CleanTech"], timeline: "Always open", funding: "Varies" },
  { name: "Kosmos Ventures", description: "Perth-based VC. Tech, software, and AI. Good option if you're in WA.", url: "https://kosmosventures.com", state: "WA", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Varies" },
  { name: "ACTivate Capital", description: "Canberra-focused. Defence, quantum computing, and AI. For government or defence-related tech.", url: "https://www.epicorp.com.au", state: "ACT", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["Defence", "DeepTech"], timeline: "Always open", funding: "Varies" },
  { name: "H2 Ventures", description: "Australia's fintech specialist. Money, banking, payments, or insurance.", url: "https://www.h2.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "Always open", funding: "Up to $500K" },
  { name: "Skalata Ventures", description: "Works hands-on with founders. Focused on sustainable growth, not just raising more money.", url: "https://skalata.vc", state: "VIC", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Always open", funding: "Varies" },

  // ============================================================
  // ANGEL NETWORKS (Funding)
  // ============================================================
  { name: "Sydney Angels", description: "Wealthy individuals who invest their own money in startups. Monthly pitch events. You give up ownership in exchange for cash.", url: "https://www.sydneyangels.net.au", state: "NSW", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly events", funding: "Varies" },
  { name: "Melbourne Angels", description: "Same concept as Sydney Angels but for Melbourne startups. Monthly pitch events.", url: "https://melbourneangels.com", state: "VIC", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly events", funding: "Varies" },
  { name: "Brisbane Angels", description: "Queensland's angel investor network. Regular pitch nights.", url: "https://www.brisbaneangels.com.au", state: "QLD", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly events", funding: "Varies" },
  { name: "Adelaide Angels", description: "South Australia's angel investor network.", url: "https://adelaideangels.com.au", state: "SA", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly events", funding: "Varies" },
  { name: "Perth Angels", description: "Western Australia's angel network. Invests in local WA startups.", url: "https://perthangels.com.au", state: "WA", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly events", funding: "Varies" },
  { name: "Startup & Angels", description: "Paid networking events connecting startups with investors. Not the investor — the event organiser.", url: "https://www.startupandangels.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Regular events", funding: "-" },

  // ============================================================
  // ALTERNATIVE FINANCING (Funding)
  // ============================================================
  { name: "R&D Capital Partners", description: "Get your R&D tax refund now instead of waiting until tax time. They advance you cash and collect when your refund comes. No ownership given up.", url: "https://rdcapital.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "$50K - $5M" },
  { name: "Radium Capital", description: "Australia's largest R&D financing. Advances your expected tax refund so you get money sooner. No ownership.", url: "https://radiumcapital.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "$50K - $10M" },
  { name: "ScotPac", description: "Invoice financing. If customers owe you money, they pay you now (minus a fee) and collect from your customers later.", url: "https://www.scotpac.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "Varies" },
  { name: "Earlypay", description: "Get cash from unpaid invoices now instead of waiting 30-60 days.", url: "https://earlypay.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "Varies" },
  { name: "Judo Bank", description: "Bank built for small businesses. More likely to lend to startups than big banks.", url: "https://www.judo.bank", state: "National", category: "Investor", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "$250K+" },

  // ============================================================
  // COMPETITIONS & AWARDS (Funding)
  // ============================================================
  { name: "Startup World Cup - Australia", description: "Pitch competition. Australian winner goes to San Francisco for US$1M grand prize.", url: "https://www.startupworldcup.io", state: "National", category: "Competition", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "US$1M grand prize" },
  { name: "SXSW Sydney Pitch", description: "Win a trip to pitch at SXSW in Austin or London. Great exposure to international investors.", url: "https://www.sxswsydney.com/participate/pitch", state: "NSW", category: "Competition", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "Trip + exposure" },
  { name: "StartCon - Pitch for $1 Million", description: "Asia Pacific's largest startup pitch competition. $1M investment prize.", url: "https://www.startcon.com/pitch", state: "National", category: "Competition", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "$1M" },
  { name: "Peter Farrell Cup (UNSW)", description: "$100K prize pool for UNSW-connected founders. Great for student founders.", url: "https://unswfounders.com/peter-farrell-cup", state: "NSW", category: "Competition", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "June 2026", funding: "Up to $100K" },
  { name: "Australian Technologies Competition", description: "Free entry for tech scaleups. Win $100K investment package.", url: "https://www.austechcomp.com", state: "National", category: "Competition", need: "Funding", stages: ["Efficiency", "Scale"], identity: ["Tech"], timeline: "2026 dates TBA", funding: "$100K" },
  { name: "InnovationACT", description: "Canberra pitch competition. $10K prize. Open to ANU and UC students/staff.", url: "https://cbrin.com.au/innovation-act/", state: "ACT", category: "Competition", need: "Funding", stages: ["Idea"], identity: [], industry: [], timeline: "Annual", funding: "$10K" },
  { name: "Smart50 Awards", description: "Awards for Australia's 50 fastest-growing SMEs. Great PR if you win.", url: "https://www.smartcompany.com.au/smart50-awards-2025/", state: "National", category: "Competition", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Mid-2026", funding: "$15K + recognition" },
  { name: "Australian Business Awards (ABA100)", description: "Categories include Start-Up of the Year. Winning gives credibility for marketing.", url: "https://australianbusinessawards.com.au/", state: "National", category: "Competition", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "July 2026", funding: "Recognition" },
  { name: "InnovationAus Awards for Excellence", description: "Awards for tech companies. AI, health, renewable energy categories.", url: "https://www.innovationausawards.com.au/", state: "National", category: "Competition", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech", "CleanTech", "HealthTech"], timeline: "2026 dates TBA", funding: "Recognition" },

  // ============================================================
  // ACCELERATORS - National (Programs)
  // ============================================================
  { name: "Startmate Accelerator", description: "Australia's top startup bootcamp. 12 weeks of mentoring from successful founders. Very competitive — 25 picked from 700+ applications. You get $120K cash but give up 8% ownership.", url: "https://www.startmate.com/accelerator", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "2 intakes per year", funding: "$120K for 8% ownership" },
  { name: "Antler Australia", description: "Different approach — you can apply even without a business idea. 5-week fast-track program. If they invest: $225K but $68K fee and 12% ownership, so you walk away with ~$157K.", url: "https://www.antler.co/location/australia", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Multiple cohorts", funding: "$157K net for 12% ownership" },
  { name: "Techstars Sydney", description: "Part of global Techstars. 13-week program with worldwide network of founders and investors.", url: "https://www.techstars.com/accelerators/sydney", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "Annual cohort", funding: "$120K for 6-8% ownership" },
  { name: "Y Combinator", description: "World's most famous accelerator (Airbnb, Stripe, Dropbox). 3 months in San Francisco. Extremely competitive but life-changing if accepted.", url: "https://www.ycombinator.com", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "2 batches per year", funding: "$500K for 7% ownership" },
  { name: "Google for Startups Accelerator: AI First", description: "Free 10-week program for AI startups. No ownership taken. Plus up to $350K in Google Cloud credits.", url: "https://startup.google.com/programs/accelerator/ai-first/australia", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Sep-Nov", funding: "Free + $350K cloud credits" },
  { name: "Founder Institute", description: "Part-time accelerator you can do while working. 4-month program. You give 4% ownership when you graduate.", url: "https://fi.co/australia", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Multiple cohorts", funding: "4% on graduation" },
  { name: "muru-D", description: "Run by Telstra. Good for startups working on 5G, IoT, or telecom tech. Corporate connections.", url: "https://www.telstra.com.au/business-enterprise/muru-d", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Various programs", funding: "Varies" },
  { name: "Stone & Chalk", description: "Australia's largest fintech hub. Sydney, Melbourne, Adelaide. Coworking community with mentoring and investor access.", url: "https://www.stoneandchalk.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "Join anytime", funding: "-", cost: "From $600/month" },

  // ============================================================
  // ACCELERATORS - Industry Specialist (Programs)
  // ============================================================
  { name: "Cicada Innovations", description: "For 'deep tech' — biotech, medical devices, advanced materials. They have actual labs you can use. Sydney-based.", url: "https://www.cicadainnovations.com", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech", "HealthTech"], timeline: "Apply anytime", funding: "-", cost: "From $500/month" },
  { name: "EnergyLab", description: "Australia's biggest climate tech accelerator. Energy, carbon, sustainability — this is your community.", url: "https://energylab.org.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["CleanTech"], timeline: "Various programs", funding: "Varies" },
  { name: "LawTech Hub by Lander & Rogers", description: "Free 6-month program for legal tech startups. No ownership taken. Run by a law firm.", url: "https://www.landers.com.au/legal-innovation/lawtech-hub", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Legal"], timeline: "Annual intake", funding: "Equity-free" },
  { name: "MedTech Actuator", description: "6-month accelerator for medical tech — devices, biotech, health software. Connects you with healthcare industry.", url: "https://medtechactuator.com", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["HealthTech"], timeline: "March intake", funding: "Pathway to $3M+" },
  { name: "CyRise", description: "Australia's only cybersecurity accelerator. 13 weeks. Access to companies needing security solutions.", url: "https://cyrise.co", state: "VIC", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "Annual intake", funding: "$50K" },
  { name: "SparkLabs Cultiv8", description: "AgTech and food tech. Based in Orange, NSW. 3-month program for farming and food innovation.", url: "https://sparklabscultiv8.com", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: ["AgTech"], timeline: "Annual intake", funding: "$100K" },
  { name: "The Melt", description: "For hardware startups — physical products, electronics, robotics. Helps with product AND business model.", url: "https://themelt.com.au", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech"], timeline: "Apply anytime", funding: "Varies" },
  { name: "Remarkable Australia+ Accelerator", description: "16 weeks for startups building tech for disability, health, and aged care.", url: "https://remarkable.org.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: ["Disability"], industry: ["HealthTech"], timeline: "2026 dates TBA", funding: "Varies" },
  { name: "SheStarts", description: "Accelerator for women tech founders. Previously run by BlueChilli. Check website for current status.", url: "https://shestarts.com", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: ["Women"], industry: [], timeline: "Check website", funding: "Varies" },
  { name: "HCF Catalyst", description: "Run by health insurer HCF. For startups improving health outcomes.", url: "https://www.hcf.com.au/about-us/about-HCF/catalyst", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["HealthTech"], timeline: "Mar-Apr", funding: "Varies" },

  // ============================================================
  // ACCELERATORS - Regional & University (Programs)
  // ============================================================
  { name: "MAP (Melbourne Accelerator Program)", description: "Free 6-month accelerator for University of Melbourne-connected founders. $20K grant, no ownership taken.", url: "https://themap.co", state: "VIC", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Aug-Jan", funding: "$20K grant (equity-free)" },
  { name: "UNSW 10x Accelerator", description: "5-month program for UNSW students, staff, and alumni. $20K microgrant, no ownership.", url: "https://www.founders.unsw.edu.au/10x-accelerator", state: "NSW", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Feb-Jun", funding: "$20K grant (equity-free)" },
  { name: "INCUBATE (Sydney Uni)", description: "Free accelerator for anyone with a Sydney Uni connection. Mentoring and workspace.", url: "https://incubate.org.au", state: "NSW", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Multiple intakes", funding: "-" },
  { name: "PLUS EIGHT Accelerator", description: "Adelaide accelerator backed by local government and private partners. Focus on tech scaleups.", url: "https://pluseight.com.au", state: "SA", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Apply anytime", funding: "Varies" },
  { name: "Venture Catalyst Space", description: "For space and space-adjacent tech startups. Run by the University of South Australia.", url: "https://venturecatalyst.com.au", state: "SA", category: "University", need: "Programs", stages: ["Validation"], identity: [], industry: ["DeepTech", "Defence"], timeline: "Annual intake", funding: "Varies" },
  { name: "StartNT", description: "Darwin's startup hub. Events, mentoring, and connections for NT founders.", url: "https://startnt.com.au", state: "NT", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "LaunchVic Basecamp", description: "Regional Victoria accelerator program. For founders outside Melbourne.", url: "https://launchvic.org", state: "VIC", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: ["Regional"], industry: [], timeline: "Check website", funding: "Varies" },
  { name: "Runway Geelong", description: "Geelong's startup hub. Coworking, events, and mentoring for regional founders.", url: "https://runwaygeelong.org.au", state: "VIC", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Regional"], industry: [], timeline: "-", funding: "-" },
  { name: "River City Labs", description: "Brisbane's original startup hub. Coworking, programs, and community for QLD founders.", url: "https://rivercitylabs.net", state: "QLD", category: "Community", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Tank Stream Labs", description: "Sydney CBD coworking for tech startups. Community and events.", url: "https://www.tankstreamlabs.com", state: "NSW", category: "Community", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "-", funding: "-", cost: "Membership required" },
  { name: "ThincLab Adelaide", description: "University of Adelaide's startup incubator. Student and alumni founders.", url: "https://www.adelaide.edu.au/thinclab", state: "SA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Enterprize", description: "Melbourne CBD startup hub with coworking, events, and accelerator programs.", url: "https://www.enterprize.com", state: "VIC", category: "Community", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "GRIFFIN", description: "Adelaide accelerator for early-stage tech startups.", url: "https://www.griffinaccelerator.com.au", state: "SA", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "Check website", funding: "Varies" },
  { name: "KILN", description: "Hobart's startup incubator. Support for Tasmanian founders.", url: "https://www.kilnincubator.com", state: "TAS", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // UNIVERSITY PROGRAMS (Programs)
  // ============================================================
  { name: "Monash Generator", description: "Free programs for Monash students and alumni. Grants up to $20K available.", url: "https://www.monash.edu/entrepreneurship", state: "VIC", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Various programs", funding: "Up to $20K" },
  { name: "QUT bluebox", description: "Queensland University of Technology's startup incubator. Free for QUT-connected founders.", url: "https://www.qut.edu.au/study/student-life/student-news-and-events/bluebox", state: "QLD", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "UQ Ventures", description: "University of Queensland's entrepreneurship hub. Programs and grants for UQ founders.", url: "https://ventures.uq.edu.au", state: "QLD", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "Grants available" },
  { name: "CERI (Centre for Entrepreneurial Research and Innovation)", description: "Perth-based incubator connected to WA universities. Programs and mentoring.", url: "https://www.ceri.com.au", state: "WA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "UWA Innovation Quarter", description: "University of Western Australia's innovation precinct. Programs and workspace for WA founders.", url: "https://www.innovation.uwa.edu.au", state: "WA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "iAccelerate (UOW)", description: "University of Wollongong's accelerator. 6-month program with $10K seed grant.", url: "https://www.iaccelerate.com.au", state: "NSW", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: ["Regional"], industry: [], timeline: "Various intakes", funding: "$10K seed grant" },
  { name: "Flinders NVI (New Ventures Institute)", description: "Flinders University's innovation hub. Programs for SA founders.", url: "https://www.flinders.edu.au/nvi", state: "SA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Western Sydney Launchpad", description: "Western Sydney University's startup program. Supports diverse founders.", url: "https://www.westernsydney.edu.au/launchpad", state: "NSW", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "RMIT Activator", description: "RMIT's entrepreneurship hub. Events, mentoring, and programs.", url: "https://www.rmit.edu.au/activator", state: "VIC", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Curtin Ignition", description: "Curtin University's flagship startup program. 8-week intensive for WA founders.", url: "https://ignition.curtin.edu.au", state: "WA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "2 intakes per year", funding: "-" },

  // ============================================================
  // CORPORATE PROGRAMS (Programs)
  // ============================================================
  { name: "CBA x15ventures", description: "Commonwealth Bank's venture studio. Partners with startups to build fintech products.", url: "https://www.x15.co", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "Apply anytime", funding: "Varies" },
  { name: "Westpac Reinventure", description: "Westpac's venture arm. Invests in fintech startups that could change banking.", url: "https://www.reinventure.com.au", state: "National", category: "Corporate", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["FinTech"], timeline: "Apply anytime", funding: "Varies" },
  { name: "NAB Ventures", description: "NAB's venture capital arm. Backs fintech and business tech startups.", url: "https://www.nabventures.com", state: "National", category: "Corporate", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "Apply anytime", funding: "Varies" },
  { name: "BHP Xplor", description: "BHP's accelerator for mining and resources innovation. Access to BHP as customer and investor.", url: "https://xplor.bhp.com", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech"], timeline: "Check website", funding: "Varies" },
  { name: "Woolworths W23", description: "Woolworths' innovation hub. For retail, food, and supply chain startups.", url: "https://w23.global", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Retail"], timeline: "Apply anytime", funding: "Varies" },
  { name: "Telstra Ventures", description: "Telstra's investment arm. Backs tech companies that could work with Telstra.", url: "https://www.telstraventures.com", state: "National", category: "Corporate", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Apply anytime", funding: "Varies" },
  { name: "AWS Activate", description: "Free Amazon Web Services credits for startups. Up to $100K in credits to host your product.", url: "https://aws.amazon.com/activate", state: "National", category: "Corporate", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $100K credits" },
  { name: "Microsoft for Startups", description: "Free Azure cloud credits, mentoring, and Microsoft tech support. Up to $150K in credits.", url: "https://startups.microsoft.com", state: "National", category: "Corporate", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $150K credits" },
  { name: "Google Cloud for Startups", description: "Free Google Cloud credits up to $200K, plus technical support and mentoring.", url: "https://cloud.google.com/startup", state: "National", category: "Corporate", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to $200K credits" },
  { name: "Stripe Atlas", description: "Easy way to set up a US company (Delaware C-Corp). Useful if you're raising from US investors.", url: "https://stripe.com/atlas", state: "National", category: "Corporate", need: "Advice", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "-", cost: "US$500" },

  // ============================================================
  // GOVERNMENT PORTALS & ADVICE
  // ============================================================
  { name: "Business.gov.au", description: "Central government website with all federal grants, registrations, and business advice in one place.", url: "https://business.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Grants Finder", description: "Searchable database of all government grants. Filter by state, industry, and business stage.", url: "https://business.gov.au/grants-and-programs", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "AusIndustry", description: "Government agency delivering business grants and programs. Apply for most federal grants here.", url: "https://www.industry.gov.au/ausindustry", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "LaunchVic", description: "Victoria's startup agency. Runs grants, programs, and ecosystem support.", url: "https://launchvic.org", state: "VIC", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Startup Victoria", description: "Victoria's peak body for startups. Events, advocacy, and community.", url: "https://startupvictoria.com.au", state: "VIC", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "NSW Innovation and Productivity Council", description: "Advises NSW Government on innovation. Good for policy updates.", url: "https://www.investment.nsw.gov.au", state: "NSW", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Business Queensland", description: "Queensland Government's business portal. Grants, advice, and support.", url: "https://www.business.qld.gov.au", state: "QLD", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "SA Startup Ecosystem", description: "South Australia's startup hub. Events, programs, and connections.", url: "https://innovationandskills.sa.gov.au", state: "SA", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Business Tasmania", description: "Tasmanian Government's business support portal.", url: "https://www.business.tas.gov.au", state: "TAS", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "CBR Innovation Network", description: "Canberra's innovation hub. Runs programs and connects ACT startups.", url: "https://cbrin.com.au", state: "ACT", category: "Community", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "CSIRO ON Prime", description: "Free 10-week program helping researchers commercialise their science. Customer discovery focus.", url: "https://www.csiro.au/en/work-with-us/funding-programs/programs/ON-program", state: "National", category: "Government", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: ["DeepTech"], timeline: "Multiple intakes", funding: "Equity-free" },
  { name: "Austrade Landing Pads", description: "Free soft-landing spaces in 5 global cities for Australian startups expanding overseas.", url: "https://www.austrade.gov.au/landing-pads", state: "National", category: "Government", need: "Programs", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "-" },
  { name: "Australian Space Agency", description: "For space-related startups. Programs, grants, and connections.", url: "https://www.industry.gov.au/australian-space-agency", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech", "Defence"], timeline: "-", funding: "Varies" },

  // ============================================================
  // SERVICE PROVIDERS (Advice)
  // ============================================================
  { name: "The Ethics Centre", description: "Helps startups think through ethical implications of their technology. Advisory services.", url: "https://ethics.org.au", state: "National", category: "Community", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "LegalVision", description: "Online law firm with fixed-price packages for startups. Cheaper and faster than traditional lawyers.", url: "https://legalvision.com.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Sprintlaw", description: "Another online law firm for startups. Fixed prices, fast turnaround.", url: "https://sprintlaw.com.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Startup Legal Guide (by Addisons)", description: "Free online legal guide for founders. Covers company setup, fundraising, IP.", url: "https://www.startuplegalguide.com.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Fullstack Advisory", description: "Accountants who specialise in startups. Understand R&D claims, ESOP, and fundraising.", url: "https://fullstack.com.au", state: "National", category: "Community", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Standard Ledger", description: "Accountants for startups and small businesses. Cloud-based, modern approach.", url: "https://standardledger.co", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Startup Muster", description: "Annual survey of Australian startup ecosystem. Good for benchmarking and data.", url: "https://startupmuster.com", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Annual", funding: "-" },
  { name: "IP Australia", description: "Government agency for trademarks, patents, and designs. Protect your intellectual property.", url: "https://www.ipaustralia.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // COMMUNITIES & NETWORKS (Connections)
  // ============================================================
  { name: "Sydney Startups", description: "Facebook group for Sydney founders. 20K+ members. Good for questions and connections.", url: "https://www.facebook.com/groups/SydneyStartups/", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "The Startup Network", description: "Australia's largest startup community. Events across major cities.", url: "https://www.thestartupnetwork.com.au", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Startup Grind", description: "Global community with Australian chapters. Monthly events with founder speakers.", url: "https://www.startupgrind.com/australia/", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly", funding: "-" },
  { name: "Fishburners", description: "Sydney coworking and community for startups. Regular events and programs.", url: "https://fishburners.org", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "TechSydney", description: "Peak body for Sydney tech ecosystem. Events, advocacy, talent programs.", url: "https://www.techsydney.com.au", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "StartupWA", description: "Peak body for WA startups. Events and advocacy for Perth founders.", url: "https://startupwa.org", state: "WA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Spacecubed", description: "Perth's main startup hub. Coworking, events, and accelerator programs.", url: "https://www.spacecubed.com", state: "WA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Startup Tasmania", description: "Community for Tasmanian founders. Events and connections.", url: "https://startuptasmania.org.au", state: "TAS", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Girls in Tech Australia", description: "Global nonprofit empowering women in tech. Events and mentoring.", url: "https://australia.girlsintech.org", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["Women"], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "Tech Ready Women", description: "Career acceleration for women in tech. Training and community.", url: "https://techreadywomen.com.au", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation"], identity: ["Women"], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "PwC Scaleup Network", description: "PwC's program for high-growth startups. Mentoring and professional services.", url: "https://www.pwc.com.au/scaleup.html", state: "National", category: "Community", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // COWORKING & PRECINCTS
  // ============================================================
  { name: "Tech Central", description: "NSW Government's tech precinct in Sydney. Multiple buildings with startups, corporates, and research.", url: "https://www.techcentral.nsw.gov.au", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "Sydney Startup Hub", description: "Government-backed coworking in Sydney CBD. Home to many startup programs.", url: "https://sydneystartuphub.com", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Lot Fourteen", description: "Adelaide's innovation precinct. Space, defence, and tech startups. Home to Australian Space Agency.", url: "https://lotfourteen.com.au", state: "SA", category: "Community", need: "Connections", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech", "Defence"], timeline: "-", funding: "-" },
  { name: "Darwin Innovation Hub", description: "NT's main startup space. Coworking, events, and programs.", url: "https://www.innovationhub.com.au", state: "NT", category: "Community", need: "Connections", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Melbourne Connect", description: "Melbourne's innovation precinct next to University of Melbourne. Research and startups.", url: "https://melbourneconnect.com.au", state: "VIC", category: "Community", need: "Connections", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // EVENTS (Connections)
  // ============================================================
  { name: "West Tech Fest", description: "Perth's startup festival. Week of events across WA.", url: "https://www.westtechfest.com.au", state: "WA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "August 2026", funding: "-" },
  { name: "SOUTHSTART", description: "Adelaide's startup conference. Brings together SA and national ecosystem.", url: "https://www.southstart.co", state: "SA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Mar 2026", funding: "-" },
  { name: "Sunrise Festival", description: "Melbourne startup festival. Week of events, talks, and networking.", url: "https://sunrisefestival.co", state: "VIC", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "May 2026", funding: "-" },
  { name: "Spark Festival", description: "Sydney's startup festival. Two weeks of events across the city.", url: "https://sparkfestival.com.au", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Oct 2026", funding: "-" },
  { name: "S2S Summit", description: "Startup to Scaleup summit. For growth-stage founders.", url: "https://startupdaily.net", state: "National", category: "Community", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "-" },
  { name: "Intersekt", description: "Fintech conference. Brings together fintech startups, banks, and investors.", url: "https://www.intersektfestival.com", state: "VIC", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["FinTech"], timeline: "Nov 2026", funding: "-" },
  { name: "SXSW Sydney", description: "Australian version of famous Austin festival. Tech, creative, and music.", url: "https://www.sxswsydney.com", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Oct 2026", funding: "-" },
  { name: "StartCon", description: "Asia Pacific's largest startup conference. Thousands of attendees, big name speakers.", url: "https://www.startcon.com", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "-" },

  // ============================================================
  // MENTORING PROGRAMS (Advice)
  // ============================================================
  { name: "LaunchVic Office Hours", description: "Free 30-minute mentoring sessions with experienced founders and advisors.", url: "https://launchvic.org/office-hours", state: "VIC", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Book anytime", funding: "-", cost: "Free" },
  { name: "Mentoring for Growth", description: "Free government mentoring program. Matched with experienced business advisors.", url: "https://business.gov.au/expertise-and-advice/mentoring-for-growth", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "-", cost: "Free" },
  { name: "SCORE Australia", description: "Volunteer business mentors for small businesses and startups.", url: "https://www.scoreaustralia.org.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },

  // ============================================================
  // FOUNDER-SPECIFIC - Indigenous (Programs)
  // ============================================================
  { name: "Barayamal", description: "Australia's first Indigenous startup accelerator. 10-week program for Aboriginal and Torres Strait Islander founders.", url: "https://www.barayamal.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: ["Indigenous"], industry: [], timeline: "Annual intake", funding: "Equity-free grants" },
  { name: "Indigenous Business Australia (IBA)", description: "Loans, business support, and mentoring for Indigenous entrepreneurs. More accessible than banks.", url: "https://www.iba.gov.au", state: "National", category: "Government", need: "Funding", stages: ["Idea", "Validation", "Efficiency"], identity: ["Indigenous"], industry: [], timeline: "Apply anytime", funding: "Loans + support" },
  { name: "Supply Nation", description: "Connects Indigenous businesses with corporate buyers. Get certified and access contracts.", url: "https://supplynation.org.au", state: "National", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: ["Indigenous"], industry: [], timeline: "-", funding: "-" },
  { name: "Many Rivers", description: "Microfinance and business coaching for Indigenous and disadvantaged entrepreneurs.", url: "https://manyrivers.org.au", state: "National", category: "Community", need: "Funding", stages: ["Idea", "Validation"], identity: ["Indigenous"], industry: [], timeline: "Apply anytime", funding: "Microloans" },
  { name: "Aboriginal Investment NT", description: "Grants for NT Aboriginal businesses. Community and economic development.", url: "https://aboriginalinvestmentnt.com.au", state: "NT", category: "Government", need: "Funding", stages: ["Idea", "Validation"], identity: ["Indigenous"], industry: [], timeline: "Apply anytime", funding: "Varies" },
  { name: "Kinaway", description: "Victorian Aboriginal Chamber of Commerce. Certification, networking, and business support.", url: "https://kinaway.com.au", state: "VIC", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["Indigenous"], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // FOUNDER-SPECIFIC - Migrants & Refugees (Programs)
  // ============================================================
  { name: "Catalysr", description: "Free accelerator for migrants and refugees. 12-week program to launch your business.", url: "https://catalysr.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: ["Migrant"], industry: [], timeline: "Multiple intakes", funding: "Equity-free" },
  { name: "Thrive Refugee Enterprise", description: "Microloans and business coaching for refugees starting businesses.", url: "https://www.thriverefugee.org.au", state: "National", category: "Community", need: "Funding", stages: ["Idea", "Validation"], identity: ["Migrant"], industry: [], timeline: "Apply anytime", funding: "Microloans" },
  { name: "Hatch Quarter", description: "Supports culturally diverse founders. Programs and community.", url: "https://www.hatchquarter.com.au", state: "National", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Migrant"], industry: [], timeline: "-", funding: "-" },
  { name: "Ignite Small Business Start-ups (ISBS)", description: "Free program helping migrants and refugees start businesses. Training and mentoring.", url: "https://www.isbs.com.au", state: "National", category: "Community", need: "Programs", stages: ["Idea"], identity: ["Migrant"], industry: [], timeline: "-", funding: "-" },
  { name: "DEI Australia", description: "Programs for diverse entrepreneurs including migrants and underrepresented groups.", url: "https://www.dei.org.au", state: "National", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Migrant"], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // FOUNDER-SPECIFIC - Disability (Programs)
  // ============================================================
  { name: "Disability Gateway Business Services", description: "Government portal connecting people with disability to business support services.", url: "https://www.disabilitygateway.gov.au/business", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: ["Disability"], industry: [], timeline: "-", funding: "-" },
  { name: "Australian Network on Disability", description: "Helps businesses become more disability-inclusive. Resources for founders with disability.", url: "https://www.and.org.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: ["Disability"], industry: [], timeline: "-", funding: "-" },
  { name: "GetAbility", description: "Social enterprise helping people with disability into employment and entrepreneurship.", url: "https://getability.com.au", state: "National", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Disability"], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // FOUNDER-SPECIFIC - LGBTQ+ (Programs)
  // ============================================================
  { name: "Pride in Diversity", description: "LGBTQ workplace inclusion program. Resources for building inclusive companies.", url: "https://www.prideinclusionprograms.com.au", state: "National", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: ["LGBTQ+"], industry: [], timeline: "-", funding: "-" },
  { name: "Out for Australia", description: "Mentoring and networking for LGBTQ+ professionals including entrepreneurs.", url: "https://outforaustralia.org", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["LGBTQ+"], industry: [], timeline: "-", funding: "-" },
  { name: "LGBTQ+ Founders Network", description: "Australian network connecting queer founders with mentors and investors. LinkedIn group.", url: "https://www.linkedin.com/groups/12546421/", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["LGBTQ+"], industry: [], timeline: "-", funding: "-", cost: "Free" },

  // ============================================================
  // FOUNDER-SPECIFIC - Veterans (Programs)
  // ============================================================
  { name: "WithYouWithMe", description: "Tech training and job placement for veterans. Paths to entrepreneurship.", url: "https://withyouwithme.com", state: "National", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Veterans"], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "Soldier On", description: "Veteran support with business mentoring and entrepreneurship programs.", url: "https://soldieron.org.au", state: "National", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Veterans"], industry: [], timeline: "-", funding: "-" },
  { name: "RSL DefenceCare", description: "Support for veterans including business advice and financial assistance.", url: "https://rsldefencecare.org.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation"], identity: ["Veterans"], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // FOUNDER-SPECIFIC - Youth (Programs)
  // ============================================================
  { name: "Foundation for Young Australians", description: "Programs for under-25s developing business skills. Bootcamps for young founders.", url: "https://www.fya.org.au", state: "National", category: "Community", need: "Programs", stages: ["Idea"], identity: ["Youth"], industry: [], timeline: "-", funding: "-" },
  { name: "Young Change Agents", description: "Programs for young Australians creating social enterprises. Focus on positive change.", url: "https://www.youngchangeagents.com", state: "National", category: "Community", need: "Programs", stages: ["Idea", "Validation"], identity: ["Youth"], industry: [], timeline: "-", funding: "-" },
  { name: "Student Edge", description: "Platform connecting students with startup programs and competitions.", url: "https://studentedge.org", state: "National", category: "Community", need: "Connections", stages: ["Idea"], identity: ["Youth"], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // FOUNDER-SPECIFIC - Regional (Programs)
  // ============================================================
  { name: "Regional Development Australia", description: "Network across Australia supporting regional businesses. Your local RDA can connect you with opportunities.", url: "https://www.rda.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: ["Regional"], industry: [], timeline: "-", funding: "-" },
  { name: "Regional Tech Hub", description: "Connecting regional tech workers and entrepreneurs. Community outside major cities.", url: "https://regionaltechhub.com.au", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["Regional"], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "SproutX", description: "AgTech accelerator for agricultural innovation. Based regionally, focused on farm tech.", url: "https://sproutx.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: ["Regional"], industry: ["AgTech"], timeline: "-", funding: "Varies" },
  { name: "Regional Accelerator Network", description: "Network of regional accelerators and incubators. Find programs outside big cities.", url: "https://startupaus.org", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation"], identity: ["Regional"], industry: [], timeline: "-", funding: "-" },
];

// Filter options for UI (sorted alphabetically)
const filterOptions = {
  needs: ["Advice", "Connections", "Funding", "Programs"],
  states: ["ACT", "National", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"],
  categories: ["Accelerator", "Community", "Competition", "Corporate", "Government", "Grant", "Investor", "Tool", "University"],
  stages: ["Efficiency", "Idea", "Scale", "Validation"],
  identities: ["Disability", "Indigenous", "LGBTQ+", "Migrant", "Regional", "Veterans", "Women", "Youth"],
  industries: ["AgTech", "CleanTech", "DeepTech", "Defence", "FinTech", "HealthTech", "Legal", "PropTech", "Retail", "Tech"]
};

// Export for Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { directoryData, filterOptions };
}
