// Sova Unified Directory Data
// Last Updated: 2025-12-04
// Combines startup support resources and funding opportunities

const directoryData = [
  // ============================================================
  // SOVA
  // ============================================================
  { name: "Sova", description: "Holistic diagnostic tool helping founders identify gaps across key business elements, all aligned to startup failure research and evidence based best practice from leading experts.", url: "https://getsova.com.au", state: "National", category: "Tool", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },

  // ============================================================
  // GOVERNMENT GRANTS (Funding)
  // ============================================================
  { name: "Industry Growth Program", description: "Matched funding for commercialisation, early-stage and growth projects aligned with National Reconstruction Fund priorities.", url: "https://business.gov.au/grants-and-programs/industry-growth-program", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "50,000 - 5 million" },
  { name: "Business Research and Innovation Initiative (BRII)", description: "Innovative solutions for government policy and service delivery challenges. Challenge-based funding rounds.", url: "https://business.gov.au/grants-and-programs/business-research-and-innovation-initiative", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "100,000 - 1 million" },
  { name: "Entrepreneur's Programme", description: "Up to 50% matched funding for novel products/services for commercialisation. Eligibility: Revenue under $20M.", url: "https://business.gov.au/grants-and-programs", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to 1 million" },
  { name: "Export Market Development Grant (EMDG)", description: "Matched funding to help export products and services abroad. Up to 8 grants available per business.", url: "https://www.austrade.gov.au/australian/export/export-grants", state: "National", category: "Grant", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "Up to 770,000" },
  { name: "CSIRO Kick-Start Program", description: "Matched funding for R&D projects in collaboration with CSIRO. For startups and small businesses with revenue under $10M.", url: "https://www.csiro.au/en/work-with-us/funding-programs/programs/csiro-kick-start", state: "National", category: "Grant", need: "Funding", stages: ["Validation"], identity: [], industry: ["DeepTech"], timeline: "Apply anytime", funding: "Up to 50,000" },
  { name: "NSW MVP Ventures Program", description: "Early-stage startup funding for minimum viable products. $6 million allocated for 2025/26.", url: "https://www.investment.nsw.gov.au/mvp", state: "NSW", category: "Grant", need: "Funding", stages: ["Validation"], identity: [], industry: [], timeline: "Closes 21 Dec 2025", funding: "25,000 - 200,000" },
  { name: "LaunchVic Startup Grants", description: "Various programs to build Victoria's startup ecosystem including pre-accelerator grants, startup agency grants, and ecosystem activation grants.", url: "https://launchvic.org", state: "VIC", category: "Grant", need: "Funding", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "10,000 - 500,000+" },
  { name: "Advance Queensland - Ignite Ideas Fund", description: "Funding for commercialising innovative products and services in Queensland.", url: "https://advance.qld.gov.au", state: "QLD", category: "Grant", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "50,000 - 500,000" },
  { name: "SA Seed-Start Program", description: "Matched funding for early-stage tech startups in South Australia.", url: "https://www.innovationandskills.sa.gov.au", state: "SA", category: "Grant", need: "Funding", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "Opens March 2026", funding: "Up to 100,000" },
  { name: "New Industries and Innovation Fund", description: "Supporting economic diversification and innovation in Western Australia across various streams.", url: "https://www.wa.gov.au/organisation/department-of-jobs-tourism-science-and-innovation", state: "WA", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Innovation Booster Grant", description: "Up to $40K for startups/SMEs. 75% upfront payment.", url: "https://www.wa.gov.au/organisation/department-of-energy-and-economic-diversification/new-industries-and-innovation-fund-innovation-booster-grant", state: "WA", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "Up to 40,000" },
  { name: "Tasmania Business Growth Programs", description: "Various small business support grants for Tasmanian businesses.", url: "https://www.business.tas.gov.au", state: "TAS", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "ACT Priority Investment Program", description: "Supporting Canberra innovation precinct development and business growth.", url: "https://www.act.gov.au/business", state: "ACT", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "NT Business Innovation Support", description: "Business innovation support program for Northern Territory ventures.", url: "https://nt.gov.au/industry/business", state: "NT", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Business Innovation Program NT", description: "NT Government grants plus advisor support for product development and market expansion.", url: "https://nt.gov.au/industry/business-grants-funding/business-innovation-program", state: "NT", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "Up to 30,000" },

  // ============================================================
  // WOMEN FOUNDER FUNDING
  // ============================================================
  { name: "Alice Anderson Fund", description: "Investment fund for female-founded startups based in Victoria. Named after Australia's first female garage owner.", url: "https://launchvic.org/alice-anderson-fund", state: "VIC", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "-", funding: "50,000 - 500,000" },
  { name: "Queensland Female Founders Fund", description: "Matched funding (1:3 ratio) for Queensland female founders with an investor-led funding round.", url: "https://advance.qld.gov.au", state: "QLD", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "-", funding: "50,000 - 200,000" },
  { name: "Fearless Innovator Grant", description: "For South Australian women entrepreneurs. Includes Scale-Up and Accelerate grant streams.", url: "https://www.innovationandskills.sa.gov.au", state: "SA", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Opens May 2026", funding: "20,000 - 60,000" },
  { name: "Coralus (formerly SheEO)", description: "Radical generosity model offering 0% interest loans to women-led ventures, funded by a community of women Activators.", url: "https://coralus.world", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Apply anytime", funding: "50,000 - 100,000" },
  { name: "Scale Investors", description: "Angel network exclusively backing female-founded companies across Australia.", url: "https://www.scaleinvestors.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "Apply anytime", funding: "50,000 - 500,000" },
  { name: "Westpac Businesses of Tomorrow", description: "$50,000 cash grants plus mentoring for Australian businesses. Female founder stream available.", url: "https://www.westpac.com.au/business-banking/business-of-tomorrow", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "2026 dates TBA", funding: "50,000 + mentoring" },
  { name: "Westpac UNSW 10x Accelerator Scholarships", description: "$20,000 scholarships for women and non-binary founders in the UNSW 10x Accelerator program.", url: "https://www.westpac.com.au/help/community/female-founders", state: "NSW", category: "Grant", need: "Funding", stages: ["Idea", "Validation"], identity: ["Women"], industry: [], timeline: "2026 dates TBA", funding: "20,000 scholarship" },
  { name: "Boosting Female Founders", description: "Federal Government grants supporting women-led startups and small businesses to scale and grow.", url: "https://business.gov.au/grants-and-programs/boosting-female-founders-initiative", state: "National", category: "Grant", need: "Funding", stages: ["Validation", "Efficiency"], identity: ["Women"], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // VENTURE CAPITAL & ANGELS (Funding)
  // ============================================================
  { name: "Blackbird Ventures", description: "Australia's largest VC with $10B+ AUM. Pre-seed to growth stage. Portfolio includes Canva, Dovetail, Culture Amp. Hosts Sunrise Festival.", url: "https://blackbird.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Pre-seed to Growth" },
  { name: "Airtree Ventures", description: "$1.3B under management. Seed to Series B. Portfolio includes Linktree, Go1, Employment Hero. Offers Open Source VC resources.", url: "https://airtree.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Seed to Series B" },
  { name: "Square Peg Capital", description: "One of Australia's largest VCs. Focus on Australia, Israel, and Southeast Asia. Portfolio includes Fiverr, Canva, Airwallex.", url: "https://squarepegcap.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Seed to Growth" },
  { name: "Main Sequence Ventures", description: "CSIRO-backed deep tech VC investing seed to late-stage. Focus on space, climate, AI, healthcare, agtech, and industrial productivity.", url: "https://mseq.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["DeepTech", "CleanTech", "HealthTech", "AgTech"], timeline: "Always open", funding: "Seed to Growth" },
  { name: "EVP (Equity Venture Partners)", description: "Specialist Australian B2B SaaS investor. ~$300M across 4 funds. Perfect for B2B SaaS companies.", url: "https://evp.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "0.5M - 5M" },
  { name: "AfterWork Ventures", description: "Pre-seed and seed investor for AU/NZ startups. Syndicate of experienced operators.", url: "https://afterwork.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: [], timeline: "Always open", funding: "Pre-seed / Seed" },
  { name: "Tidal Ventures", description: "Australian-US VC focusing on seed-stage startups with global potential.", url: "https://tidal.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: [], timeline: "Always open", funding: "Seed" },
  { name: "Flying Fox Ventures", description: "Pre-seed and seed investor focusing on SaaS, health, and climate innovation.", url: "https://flyingfoxventures.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation"], identity: [], industry: ["Tech", "HealthTech", "CleanTech"], timeline: "Always open", funding: "Pre-seed / Seed" },
  { name: "Transition Level Investments", description: "Seed and Series A investor by Steve Baxter (Shark Tank, River City Labs founder). Equity capital + operational expertise.", url: "https://transitionlevel.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Always open", funding: "Seed / Series A" },
  { name: "Giant Leap", description: "Impact investor backing companies creating positive social and environmental outcomes.", url: "https://giantleap.com.au", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["CleanTech"], timeline: "Always open", funding: "Seed / Series A" },
  { name: "Kosmos Ventures", description: "Perth-based VC focusing on technology, SaaS, and AI startups. Seed to growth stage.", url: "https://kosmosventures.com", state: "WA", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Seed to Growth" },
  { name: "ACTivate Capital", description: "$50M VC fund by Epic Corporation. Focus on defence, quantum computing, and AI startups in Canberra region.", url: "https://www.epicorp.com.au", state: "ACT", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["Defence", "DeepTech"], timeline: "Always open", funding: "Pre-seed to Series A" },
  { name: "H2 Ventures", description: "Australia's leading fintech VC investing up to $500K in early-stage fintech startups. Strong focus on payments, lending, and insurtech.", url: "https://www.h2.vc", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "Always open", funding: "Up to 500,000" },
  { name: "Skalata Ventures", description: "Seed-stage VC with hands-on support. 'Build a business, not just a runway.' Operating partners work directly with founders.", url: "https://skalata.vc", state: "VIC", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Always open", funding: "Seed" },
  { name: "Sydney Angels", description: "100+ active angel investors. Monthly pitch nights for tech startups. Syndicated investments.", url: "https://sydneyangels.net.au", state: "NSW", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Monthly pitch nights", funding: "100,000 - 1M" },
  { name: "Melbourne Angels", description: "90+ angel investors backing early-stage ventures in Victoria.", url: "https://melbourneangels.com", state: "VIC", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly pitch nights", funding: "100,000 - 500,000" },
  { name: "Brisbane Angels", description: "Queensland-based angel network supporting local startups.", url: "https://brisbaneangels.org.au", state: "QLD", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "Monthly pitch nights", funding: "-" },
  { name: "Startup & Angels", description: "Premium networking events connecting startups with angel investors and VCs. Pitch opportunities and curated introductions.", url: "https://www.startupandangels.com", state: "National", category: "Investor", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // COMPETITIONS & AWARDS (Funding)
  // ============================================================
  { name: "Startup World Cup - Australia", description: "Winner advances to Grand Finale in San Francisco for US$1 million. Sydney and Melbourne regional rounds.", url: "https://www.startupworldcup.io", state: "National", category: "Competition", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "US 1 million (Grand Finale)" },
  { name: "SXSW Sydney Pitch", description: "Win a trip to pitch at SXSW Austin or London. 7 categories including new Student Pitch track.", url: "https://www.sxswsydney.com/participate/pitch", state: "NSW", category: "Competition", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "-" },
  { name: "StartCon - Pitch for $1 Million", description: "Asia Pacific's largest startup pitch competition in partnership with Edge196.", url: "https://www.startcon.com/pitch", state: "National", category: "Competition", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "2026 dates TBA", funding: "1 million investment" },
  { name: "Peter Farrell Cup (UNSW)", description: "$100,000 cash prize pool. AHEGS certified - appears on graduation statement.", url: "https://unswfounders.com/peter-farrell-cup", state: "NSW", category: "Competition", need: "Funding", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "June 2026", funding: "Share of 100,000" },
  { name: "Australian Technologies Competition", description: "$100,000 investment package from Scalare Partners. Free entry for tech scale-ups across 12+ sectors.", url: "https://www.austechcomp.com", state: "National", category: "Competition", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "2026 dates TBA", funding: "100,000 investment" },
  { name: "InnovationACT", description: "Annual pitch competition with $10K prize pool for ANU and UC students and staff. Gateway to Canberra's startup ecosystem.", url: "https://cbrin.com.au/innovation-act/", state: "ACT", category: "Competition", need: "Funding", stages: ["Idea"], identity: [], industry: [], timeline: "-", funding: "10,000" },
  { name: "Smart50 Awards", description: "SmartCompany's awards for Australia's 50 fastest-growing SMEs. Categories include Innovation, Rising Star, Smart & Lasting.", url: "https://www.smartcompany.com.au/smart50-awards-2025/", state: "National", category: "Competition", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Mid-2026", funding: "15,000+ in prizes" },
  { name: "Australian Business Awards (ABA100)", description: "Categories include Business Innovation, Product Innovation, Start-Up of the Year, AI Innovation, Digital Innovation.", url: "https://australianbusinessawards.com.au/", state: "National", category: "Competition", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "July 2026", funding: "-" },
  { name: "InnovationAus Awards for Excellence", description: "Technology-driven company awards across AI, renewable energy, health, and software categories.", url: "https://www.innovationausawards.com.au/", state: "National", category: "Competition", need: "Connections", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech", "CleanTech", "HealthTech"], timeline: "2026 dates TBA", funding: "-" },

  // ============================================================
  // ACCELERATORS & INCUBATORS (Programs)
  // ============================================================
  { name: "Startmate Accelerator", description: "Australia's leading accelerator. 12 weeks, ~25 startups selected from 600+ applications. Access to 170+ portfolio companies valued at $2B+.", url: "https://www.startmate.com/accelerator", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "2 cohorts per year", funding: "120,000 for 7.5% equity" },
  { name: "Antler Australia", description: "Global startup generator with presence in Sydney, Melbourne, and Brisbane. 10-week residency program for pre-idea to early-stage founders.", url: "https://www.antler.co/residency/australia", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "260,000 for 12% equity" },
  { name: "Google for Startups Accelerator: AI First", description: "10-week equity-free program for Seed to Series A AI/ML-driven platforms. Applications typically open May-June.", url: "https://startup.google.com/programs/accelerator/ai-first/australia", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "2026 dates TBA", funding: "Equity-free + credits" },
  { name: "Stone & Chalk", description: "Australia's largest fintech and innovation hub with locations in Sydney, Melbourne and Adelaide. Membership includes workspace, mentoring, and investor access.", url: "https://www.stoneandchalk.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "-", funding: "-", cost: "From $600/month" },
  { name: "Cicada Innovations", description: "Australia's leading deep tech incubator with 25+ year track record. 400+ startups, $6.1B+ raised. Custom labs in Eveleigh, Westmead HealthTechHub.", url: "https://www.cicadainnovations.com", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech", "HealthTech"], timeline: "Apply anytime", funding: "-", cost: "From $500/month" },
  { name: "EnergyLab", description: "Australia's largest climate tech accelerator. 10 programs including Climate Tech Ignite, Women in Climate fellowship. 270+ startups, 400+ mentors.", url: "https://energylab.org.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["CleanTech"], timeline: "-", funding: "-" },
  { name: "LawTech Hub by Lander & Rogers", description: "Australia's longest-running legal tech accelerator. 6-month equity-free program with masterclasses, VC access, and Legal Tech Pitch Night. 93% of graduates remain operational.", url: "https://www.landers.com.au/legal-innovation/lawtech-hub", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Legal"], timeline: "Annual intake", funding: "Equity-free" },
  { name: "Remarkable Australia+ Accelerator", description: "16-week accelerator for disability, health, and ageing technology startups.", url: "https://remarkable.org.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: ["Disability"], industry: ["HealthTech"], timeline: "2026 dates TBA", funding: "-" },
  { name: "MedTech Actuator", description: "6-month hands-on accelerator for MedTech, BioTech and HealthTech startups. Access to 150+ partners, mentors and pathway to $3M+ investment.", url: "https://medtechactuator.com/accelerator/", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["HealthTech"], timeline: "March intake", funding: "Up to 3 million+" },
  { name: "CyRise", description: "Australia's only cybersecurity accelerator. 13-week program with access to enterprise customers and security industry mentors.", url: "https://www.cyrise.co", state: "VIC", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "Annual intake", funding: "50,000+" },
  { name: "SparkLabs Cultiv8", description: "AgTech and FoodTech accelerator based in Orange, NSW. 3-month program focused on agricultural innovation.", url: "https://sparklabscultiv8.com", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: ["AgTech"], timeline: "Annual intake", funding: "100,000" },
  { name: "Melbourne Accelerator Program (MAP)", description: "Australia's leading university accelerator with 10+ years track record. Alumni have raised $300M+ and created 1,500+ jobs.", url: "https://www.themap.co", state: "VIC", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Annual intake", funding: "20,000 (equity-free)" },
  { name: "UNSW Founders 10x", description: "10-week accelerator with dedicated mentor, EIR, and program manager. Max 6 startups per cohort. $20K scholarships for women founders.", url: "https://unswfounders.com/10x-accelerator", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Annual intake", funding: "100,000 via SAFE" },
  { name: "INCUBATE Sydney", description: "Award-winning USyd program since 2012 with 100+ mentors. 220+ startups launched, $50M+ invested. Three tracks available.", url: "https://incubate.org.au", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "PLUS EIGHT", description: "Australia's largest seed-funded accelerator by Spacecubed. 50 companies across 7 cohorts, $24M follow-on investment. 70% survival rate.", url: "https://pluseight.spacecubed.com", state: "WA", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "Annual intake", funding: "Seed investment" },
  { name: "Venture Catalyst", description: "UniSA's 6-month equity-free accelerator with $10K stipend. Workshops, mentoring, free CBD coworking. You keep 100% equity and IP.", url: "https://icc.unisa.edu.au/programs/venture-catalyst/", state: "SA", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "Apply anytime", funding: "10,000 stipend" },
  { name: "StartNT Program", description: "Darwin Innovation Hub's accelerator with mentoring and connection to NT's growing innovation ecosystem.", url: "https://darwininnovationhub.com.au/innovation/start-nt-program/", state: "NT", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "Apply anytime", funding: "50,000 via SAFE" },
  { name: "Founder Institute", description: "World's largest pre-seed accelerator with Australian chapters. 4-month part-time program for working founders. 4% equity on graduation.", url: "https://fi.co/australia", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "muru-D", description: "Telstra's innovation hub for prototyping and tech ventures. 80+ startups accelerated. Expertise in 5G, IoT, AI, edge computing.", url: "https://www.telstra.com.au/business-enterprise/muru-d", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "BlueChilli / SheStarts", description: "Corporate innovation and startup accelerator running SheStarts for women founders and Future Minds for youth.", url: "https://www.bluechilli.com", state: "National", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: ["Women"], industry: [], timeline: "-", funding: "-" },
  { name: "LaunchVic Basecamp", description: "LaunchVic's program helping seed-stage startups hire their first key executives with support and resources.", url: "https://launchvic.org/programs/", state: "VIC", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Runway Geelong", description: "Regional Victorian accelerator since 2017. Bootcamp and Incubator programs. $1.80 economic return for every $1 invested.", url: "https://runwayhq.co", state: "VIC", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "River City Labs Accelerator", description: "ACS-owned Brisbane tech hub offering programs, mentorship, and investor connections.", url: "https://rivercitylabs.acs.org.au", state: "QLD", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: ["Tech"], timeline: "-", funding: "-" },
  { name: "Tank Stream Labs", description: "Sydney CBD coworking and venture services hub housing 50+ startups with investor access and community events.", url: "https://tankstreamlabs.com", state: "NSW", category: "Accelerator", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $550/month" },
  { name: "ThincLab", description: "University of Adelaide's innovation hub offering ThincSeed and ThincScale programs with mentoring and resources.", url: "https://www.adelaide.edu.au/thinclab/", state: "SA", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Enterprize Incubator", description: "15-week Elevate program using lean startup methodology. Hubs in Hobart and Launceston with gigabit internet.", url: "https://enterprize.space", state: "TAS", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "GRIFFIN Accelerator", description: "CBR Innovation Network's 3-month intensive program with structured mentoring and investor preparation.", url: "https://cbrin.com.au", state: "ACT", category: "Accelerator", need: "Programs", stages: ["Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "KILN Incubator", description: "CBR Innovation Network's foundational program combining mentorship, coworking, and learning for early-stage founders.", url: "https://cbrin.com.au", state: "ACT", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // UNIVERSITY PROGRAMS (Programs)
  // ============================================================
  { name: "Monash Generator", description: "Monash University's entrepreneurship program helping students and staff move from idea to prototype.", url: "https://www.monash.edu/entrepreneurship/programs/accelerator", state: "VIC", category: "University", need: "Programs", stages: ["Idea"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "QUT bluebox", description: "Queensland University of Technology's innovation hub offering business coaching and startup support.", url: "https://qutbluebox.com.au", state: "QLD", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "UQ Ventures", description: "University of Queensland's entrepreneurship hub with global immersion programs in Hanoi, Shenzhen and San Francisco.", url: "https://ventures.uq.edu.au", state: "QLD", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "CERI", description: "WA social enterprise since 2016. 1,150+ graduates, $114M combined valuations. Programs include Entrepreneurial Mindset Bootcamp.", url: "https://www.ceri.org.au", state: "WA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "UWA Innovation Quarter", description: "University of Western Australia's innovation hub supporting students and alumni with startup programs.", url: "https://www.innovation.uwa.edu.au", state: "WA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "iAccelerate", description: "University of Wollongong's startup hub serving the Illawarra region with incubation programs and coworking.", url: "https://www.uow.edu.au/engage/uow-iaccelerate/", state: "NSW", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Flinders NVI", description: "Flinders University's New Venture Institute supporting student and staff entrepreneurs.", url: "https://www.flinders.edu.au/nvi", state: "SA", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Western Sydney Launchpad", description: "Western Sydney University's startup hub providing incubation, mentoring, and resources.", url: "https://www.westernsydney.edu.au/launch-pad", state: "NSW", category: "University", need: "Programs", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-" },

  // ============================================================
  // CORPORATE PROGRAMS (Programs)
  // ============================================================
  { name: "CBA x15ventures", description: "CommBank's venture builder backing startups for 15M customers. Builds, buys, and invests in digital ventures.", url: "https://www.x15ventures.com.au", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "-", funding: "-" },
  { name: "Westpac Reinventure", description: "$150M VC fund investing in fintech across Asia-Pacific. 'Founder-first' approach backing early-stage companies.", url: "https://reinventure.com.au", state: "National", category: "Corporate", need: "Funding", stages: ["Efficiency", "Scale"], identity: [], industry: ["FinTech"], timeline: "Always open", funding: "-" },
  { name: "NAB Ventures", description: "NAB's corporate venture arm investing in business finance, open banking, and fintech innovation.", url: "https://www.nab.com.au/about-us/nab-ventures", state: "National", category: "Corporate", need: "Funding", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "Always open", funding: "-" },
  { name: "BHP Xplor", description: "BHP's accelerator for mining technology startups. Rapid prototyping and access to mining industry expertise.", url: "https://www.bhp.com/about/our-businesses/xplor", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["DeepTech"], timeline: "May-Jun", funding: "-" },
  { name: "HCF Catalyst", description: "HCF's healthtech accelerator supporting startups improving health outcomes for Australians.", url: "https://www.hcf.com.au/about-us/about-HCF/catalyst", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["HealthTech"], timeline: "Mar-Apr", funding: "-" },
  { name: "Woolworths W23", description: "Woolworths' venture arm investing in retail, supply chain, and food technology startups.", url: "https://www.w23.vc", state: "National", category: "Corporate", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Retail", "AgTech"], timeline: "Always open", funding: "-" },
  { name: "Telstra Ventures", description: "Telstra's global VC arm investing Series B+ in technology companies. Part of muru-D ecosystem.", url: "https://telstraventures.com", state: "National", category: "Corporate", need: "Funding", stages: ["Scale"], identity: [], industry: ["Tech"], timeline: "Always open", funding: "Series B+" },
  { name: "AWS Activate", description: "Up to $100K AWS credits for startups backed by accelerators or VCs. Cloud infrastructure, technical support.", url: "https://aws.amazon.com/startups/credits", state: "National", category: "Corporate", need: "Programs", stages: ["Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "Apply anytime", funding: "Up to 100,000 credits" },

  // ============================================================
  // GOVERNMENT ADVICE & PROGRAMS
  // ============================================================
  { name: "Business.gov.au", description: "The Australian Government's central hub for business information, grants finder, registration tools and compliance guides.", url: "https://business.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Grants and Programs Finder", description: "Searchable database of grants and assistance from federal, state and local governments.", url: "https://business.gov.au/grants-and-programs", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "AusIndustry", description: "Federal government's innovation programs including the R&D Tax Incentive, offering up to 43.5% refundable tax offset.", url: "https://www.industry.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "LaunchVic", description: "Victoria's dedicated startup agency with over $40M invested. Runs accelerator programs, grants, and Office Hours free mentoring.", url: "https://launchvic.org", state: "VIC", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "NSW Innovation", description: "NSW Government's innovation hub including Tech Central precinct, startup grants, and programs.", url: "https://www.nsw.gov.au/business-and-economy/innovation", state: "NSW", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Business Queensland", description: "Queensland's business support portal featuring Advance Queensland initiatives and Mentoring for Growth program.", url: "https://www.business.qld.gov.au", state: "QLD", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "SA Startup Ecosystem", description: "South Australia's startup support including Venture Catalyst programs and the Lot Fourteen innovation precinct.", url: "https://statedevelopment.sa.gov.au", state: "SA", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "Business Tasmania", description: "Tasmania's business support portal with Business Growth Loan Scheme and incubator programs.", url: "https://www.business.tas.gov.au", state: "TAS", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "CBR Innovation Network", description: "ACT's innovation hub running GRIFFIN Accelerator, KILN Incubator, and connecting Canberra's startup community.", url: "https://cbrin.com.au", state: "ACT", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-" },
  { name: "CSIRO ON Prime", description: "Research commercialisation program for deep tech ventures.", url: "https://www.csiro.au/en/work-with-us/funding-programs/innovation-programs/on-prime", state: "National", category: "Government", need: "Programs", stages: ["Validation"], identity: [], industry: ["DeepTech"], timeline: "Jan/Feb, Jun/Jul", funding: "-" },
  { name: "Austrade Landing Pads", description: "Free 90-day residency in global tech hubs for Australian startups looking to expand internationally.", url: "https://www.austrade.gov.au/landingpads", state: "National", category: "Government", need: "Programs", stages: ["Efficiency", "Scale"], identity: [], industry: [], timeline: "Apply anytime", funding: "-" },
  { name: "Export Finance Australia", description: "Government export credit agency providing finance solutions for Australian exporters and international projects.", url: "https://www.exportfinance.gov.au", state: "National", category: "Government", need: "Funding", stages: ["Scale"], identity: [], industry: [], timeline: "Always open", funding: "-" },
  { name: "NEIS", description: "Training, mentoring, income support for new businesses. Support for people with disability.", url: "https://business.gov.au/grants-and-programs/new-enterprise-incentive-scheme-neis", state: "National", category: "Government", need: "Programs", stages: ["Idea"], identity: ["Disability"], industry: [], timeline: "Apply anytime", funding: "-" },
  { name: "ASIC Innovation Hub", description: "Helps fintech and regtech startups navigate regulatory requirements. Informal guidance on licensing, compliance and the regulatory sandbox.", url: "https://asic.gov.au/for-business/innovation-hub/", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency"], identity: [], industry: ["FinTech"], timeline: "-", funding: "-", cost: "Free" },
  { name: "IP Australia", description: "Register patents, trademarks and designs. Resources for understanding IP strategy and protecting innovations.", url: "https://www.ipaustralia.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $100" },
  { name: "ARENA", description: "Australian Renewable Energy Agency funding for clean energy innovation. Grants from $100K to $50M for renewable energy projects.", url: "https://arena.gov.au/funding/", state: "National", category: "Government", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["CleanTech"], timeline: "-", funding: "100,000 - 50 million" },
  { name: "Business Victoria", description: "Free virtual advice sessions, Small Business Bus, and mentoring programs for Victorian businesses.", url: "https://business.vic.gov.au", state: "VIC", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "NSW Small Business Commissioner", description: "Free webinars, guides, and dispute resolution services for NSW small businesses.", url: "https://www.smallbusiness.nsw.gov.au", state: "NSW", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "ASBFEO", description: "Australian Small Business and Family Enterprise Ombudsman. Dispute resolution and advocacy for small businesses dealing with government or large companies.", url: "https://www.asbfeo.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "ASBAS Digital Solutions", description: "Low-cost digital advisory services including workshops, webinars and 5 hours of 1-on-1 mentoring for $110. Covers social media, AI, cybersecurity.", url: "https://business.gov.au/expertise-and-advice/digital-solutions-australian-small-business-advisory-services", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "$110 for 5hrs" },
  { name: "Small Business Mentoring Service (SBMS)", description: "Volunteer mentors providing low-cost business advice. 6-session Starting a Business program and ongoing mentoring.", url: "https://www.sbms.org.au", state: "VIC", category: "Community", need: "Advice", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $65/session" },
  { name: "Small Business Cyber Resilience Service", description: "Free tailored support to help small businesses build cyber resilience and recover from cyber incidents.", url: "https://business.gov.au/online/cyber-security/small-business-cyber-resilience-service", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Global Talent Visa", description: "National Innovation Visa for exceptionally talented migrants in future-focused fields. Pathway to permanent residency for global talent.", url: "https://immi.homeaffairs.gov.au/visas/working-in-australia/visas-for-innovation/national-innovation-visa", state: "National", category: "Government", need: "Programs", stages: ["Efficiency", "Scale"], identity: [], industry: ["Tech", "DeepTech"], timeline: "-", funding: "-" },
  { name: "ATO Small Business", description: "Tax guidance for startups including GST, PAYG, super obligations and the instant asset write-off. Small business tax concessions explained.", url: "https://www.ato.gov.au/businesses-and-organisations/getting-started/small-business", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "R&D Tax Incentive", description: "Up to 43.5% refundable tax offset for eligible R&D activities. Cash refund for loss-making startups with turnover under $20M.", url: "https://business.gov.au/grants-and-programs/research-and-development-tax-incentive", state: "National", category: "Government", need: "Funding", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "Register by 30 Apr", funding: "Up to 43.5% offset" },
  { name: "Fair Work Ombudsman", description: "Employment compliance guidance for startups. Pay rates, awards, hiring employees, and the Small Business Fair Dismissal Code.", url: "https://smallbusiness.fairwork.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "ACCC Small Business", description: "Competition and consumer law guidance. Understand your rights dealing with suppliers, franchising, and unfair contract terms.", url: "https://www.accc.gov.au/business/small-business", state: "National", category: "Government", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },

  // ============================================================
  // ADVICE & ETHICS
  // ============================================================
  { name: "Ethi-call (The Ethics Centre)", description: "Free, confidential ethics helpline. 1-hour sessions with ethics counsellors to work through difficult business decisions and ethical dilemmas.", url: "https://ethics.org.au/consulting-and-leadership/ethi-call/", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "The Ethics Centre", description: "Not-for-profit helping businesses navigate ethical challenges. Leadership programs, consulting, and the free Ethi-call helpline.", url: "https://ethics.org.au", state: "National", category: "Community", need: "Advice", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Varies" },
  { name: "LegalVision", description: "Online law firm with fixed-fee legal services for startups. Company setup, shareholder agreements, IP protection, employment contracts.", url: "https://legalvision.com.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Fixed fees" },
  { name: "Sprintlaw", description: "Online startup lawyers offering affordable fixed-fee legal services. Terms of service, privacy policies, founder agreements.", url: "https://sprintlaw.com.au", state: "National", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Fixed fees" },
  { name: "Startup Legal Guide (Airtree)", description: "Open-source legal templates and guides for Australian startups. SAFE notes, term sheets, cap tables, employment agreements.", url: "https://www.airtree.vc/open-source-vc", state: "National", category: "Tool", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Startup Muster", description: "Annual survey and report mapping Australia's startup ecosystem. Data on funding, industries, founder demographics.", url: "https://startupmuster.com", state: "National", category: "Tool", need: "Advice", stages: ["Idea", "Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },

  // ============================================================
  // COMMUNITY - Networks, Hubs & Events (Connections)
  // ============================================================
  { name: "Sydney Startups", description: "Australia's largest online startup community with 60K+ members. Active Slack channel for Q&A and founder connections.", url: "https://sydneystartups.com", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "The Startup Network", description: "75K+ member community across Melbourne and Sydney. Regular networking events, pitch nights, and founder meetups.", url: "https://thestartupnetwork.com.au", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Startup Grind", description: "Global startup community with Australian chapters in Sydney, Melbourne, Brisbane. Monthly fireside chats with founders.", url: "https://www.startupgrind.com/sydney/", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Fishburners", description: "Australia's largest startup community with coworking in Sydney, Brisbane and Adelaide. 200+ events per year.", url: "https://fishburners.org", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $99/month" },
  { name: "TechSydney", description: "Sydney's tech ecosystem hub working to build Sydney into a Top 10 global startup ecosystem. Free membership.", url: "https://www.techsydney.com.au", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "-", funding: "-", cost: "Free" },
  { name: "StartupWA", description: "WA's peak startup body since 2015. Free membership, policy advocacy, and ecosystem connections.", url: "https://startupwa.org", state: "WA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Spacecubed", description: "Western Australia's leading startup hub offering coworking, accelerator programs, and community events.", url: "https://spacecubed.com", state: "WA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $49/month" },
  { name: "Startup Tasmania", description: "Volunteer-run peak body connecting Tasmania's startup community with resources and networking events.", url: "https://startuptasmania.com", state: "TAS", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Girls in Tech Australia", description: "Global organisation empowering women in tech with quarterly events, networking, and professional development.", url: "https://australia.girlsintech.org", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["Women"], industry: ["Tech"], timeline: "-", funding: "-", cost: "Free" },
  { name: "Tech Ready Women", description: "Training and mentoring program preparing women for careers and leadership in the tech industry.", url: "https://techreadywomen.com.au", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation"], identity: ["Women"], industry: ["Tech"], timeline: "-", funding: "-", cost: "From $297" },
  { name: "PwC Scaleup Network", description: "Advisory program for high-growth companies with $500K+ ARR. Access to PwC expertise and resources.", url: "https://www.pwc.com.au", state: "National", category: "Community", need: "Connections", stages: ["Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "By invitation" },
  { name: "Tech Central", description: "Sydney's innovation precinct at 477 Pitt Street. Australia's highest concentration of tech companies.", url: "https://www.nsw.gov.au/business-and-economy/innovation", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Tech"], timeline: "-", funding: "-", cost: "-" },
  { name: "Sydney Startup Hub", description: "NSW Government's 17,000sqm innovation precinct across 11 floors in Sydney CBD.", url: "https://www.investment.nsw.gov.au/sydney-startup-hub/", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $400/month" },
  { name: "Lot Fourteen", description: "Adelaide's 7-hectare innovation neighbourhood featuring 80+ organisations and Australia's Space Discovery Centre.", url: "https://lotfourteen.com.au", state: "SA", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["Defence", "DeepTech"], timeline: "-", funding: "-", cost: "-" },
  { name: "Darwin Innovation Hub", description: "Northern Territory's main startup hub running the StartNT accelerator program.", url: "https://darwininnovationhub.com.au", state: "NT", category: "Community", need: "Connections", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $220/month" },
  { name: "LaunchVic Office Hours", description: "Free 45-minute 1-on-1 mentoring sessions with experienced founders, investors, and industry experts.", url: "https://launchvic.org", state: "VIC", category: "Community", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "Mentoring for Growth", description: "Free Queensland Government program connecting founders with volunteer business experts for strategic advice.", url: "https://www.business.qld.gov.au", state: "QLD", category: "Community", need: "Advice", stages: ["Idea", "Validation"], identity: [], industry: [], timeline: "-", funding: "-", cost: "Free" },
  { name: "West Tech Fest", description: "Australia's longest-running tech festival held annually in Perth. Networking, pitch sessions, investor meetings.", url: "https://westtechfest.com.au/", state: "WA", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: ["Tech"], timeline: "December", funding: "-", cost: "From $50" },
  { name: "SOUTHSTART", description: "Australia's #1 entrepreneurship event held in Adelaide. 3-day innovation festival with masterclasses and networking.", url: "https://southstart.co", state: "SA", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "March", funding: "-", cost: "From $299" },
  { name: "Sunrise Festival (Blackbird)", description: "ANZ's premier startup festival hosted by Blackbird Ventures in Sydney. Includes Startmate Demo Day.", url: "https://www.thesunrise.live/", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "-", funding: "-", cost: "From $200" },
  { name: "Spark Festival", description: "Week-long festival 'by startups, for startups' across Sydney and Regional NSW.", url: "https://sparkfestival.co/", state: "NSW", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: [], industry: [], timeline: "September", funding: "-", cost: "Free - $50" },
  { name: "Startup 2 Scaleup Summit (S2S)", description: "Full-day summit with pitch competition, Investor Lounge, talks, and demos.", url: "https://www.s2ssummit.com/", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "August", funding: "-", cost: "From $150" },
  { name: "Intersekt Festival", description: "Australia's largest fintech gathering with hubs, accelerators, policymakers, and investors.", url: "https://intersektfestival.com/", state: "VIC", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: ["FinTech"], timeline: "September", funding: "-", cost: "From $100" },
  { name: "SXSW Sydney", description: "Tech, film, music, games, culture festival. Innovation across industries with international attendance.", url: "https://www.sxswsydney.com/", state: "NSW", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: [], industry: [], timeline: "October", funding: "-", cost: "From $350" },

  // ============================================================
  // FOUNDER-SPECIFIC PROGRAMS
  // ============================================================
  { name: "Barayamal", description: "World-leading First Nations entrepreneurship organisation. Events, education, mentoring, and research.", url: "https://barayamal.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: ["Indigenous"], industry: [], timeline: "-", funding: "-" },
  { name: "Indigenous Business Australia", description: "Government agency providing loans up to $100K, business workshops, and support for First Nations entrepreneurs.", url: "https://iba.gov.au", state: "National", category: "Government", need: "Funding", stages: ["Idea", "Validation", "Efficiency"], identity: ["Indigenous"], industry: [], timeline: "Apply anytime", funding: "Up to 100,000" },
  { name: "Supply Nation", description: "Australia's largest database of verified Indigenous businesses. Connects suppliers with procurement opportunities.", url: "https://supplynation.org.au", state: "National", category: "Community", need: "Connections", stages: ["Validation", "Efficiency", "Scale"], identity: ["Indigenous"], industry: [], timeline: "-", funding: "-" },
  { name: "Many Rivers", description: "Free business coaching and microfinance for First Nations and disadvantaged entrepreneurs.", url: "https://manyrivers.org.au", state: "National", category: "Government", need: "Programs", stages: ["Idea", "Validation"], identity: ["Indigenous"], industry: [], timeline: "-", funding: "-" },
  { name: "Aboriginal Investment NT", description: "NT-based organisation providing grants up to $100K and business support for Aboriginal entrepreneurs.", url: "https://www.aboriginalinvestment.org.au", state: "NT", category: "Government", need: "Funding", stages: ["Idea", "Validation"], identity: ["Indigenous"], industry: [], timeline: "-", funding: "Up to 100,000" },
  { name: "Catalysr", description: "Western Sydney incubator empowering migrant and refugee entrepreneurs since 2016. 1,045+ migrapreneurs supported.", url: "https://catalysr.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: ["Migrant"], industry: [], timeline: "-", funding: "-" },
  { name: "Thrive Refugee Enterprise", description: "Loans up to $50K and business support specifically for refugees and asylum seekers.", url: "https://www.thriverefugeeenterprise.org.au", state: "National", category: "Government", need: "Funding", stages: ["Idea", "Validation"], identity: ["Migrant"], industry: [], timeline: "-", funding: "Up to 50,000" },
  { name: "Hatch Quarter", description: "Melbourne-based advisory supporting venture growth with global market access, especially GCC expansion.", url: "https://hatchquarter.com.au", state: "National", category: "Accelerator", need: "Programs", stages: ["Idea", "Validation"], identity: ["Women", "Migrant"], industry: [], timeline: "-", funding: "-" },
  { name: "DEI Australia", description: "Diversity, equity, and inclusion charity supporting entrepreneurs and workers with disability.", url: "https://www.deiaustralia.com.au", state: "National", category: "Community", need: "Connections", stages: ["Idea", "Validation", "Efficiency"], identity: ["Disability"], industry: [], timeline: "-", funding: "-" },
  { name: "Disability Gateway", description: "Australian Government's central resource hub for people with disability, including business support.", url: "https://www.disabilitygateway.gov.au", state: "National", category: "Government", need: "Advice", stages: ["Idea", "Validation", "Efficiency"], identity: ["Disability"], industry: [], timeline: "-", funding: "-" },
];

// Filter options for UI (sorted alphabetically)
const filterOptions = {
  needs: ["Advice", "Connections", "Funding", "Programs"],
  states: ["ACT", "National", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA"],
  categories: ["Accelerator", "Community", "Competition", "Corporate", "Government", "Grant", "Investor", "Tool", "University"],
  stages: ["Efficiency", "Idea", "Scale", "Validation"],
  identities: ["Disability", "Indigenous", "Migrant", "Women"],
  industries: ["AgTech", "CleanTech", "DeepTech", "Defence", "FinTech", "HealthTech", "Legal", "Retail", "Tech"]
};
